### ISSUE TITLE
error_mx

### ISSUE THREAD

**Issue by rossibarra** [yangjl/imputeR#4]
in branch master, error_mx in utils.R should be:

`cbind(mx*matrix(c(1, 0, 0), nrow = 3,byrow=F,ncol=3),1/3)`

instead of

`cbind(mx*matrix(c(1, 0, 0), nrow = 3,byrow=F,ncol=3),1)`

throughout so that sum across kid genotypes = 1 not 3

**Comment by yangjl** [comment]
If we assume the missing rate is 0.5.
Can we use the error matrix like this with homo error=0.8 and het error=0.02?

```
 ob0   ob1   ob2 obN
```

g0 0.490 0.005 0.005 0.5
g1 0.200 0.100 0.200 0.5
g2 0.005 0.005 0.490 0.5

**Comment by yangjl** [comment]
And the overall error probs by considering error rate and Mendelian transmission?

> probs
> [[1]]
> [[1]][[1]]
>     ob0   ob1   ob2 obN
> g0 0.49 0.005 0.005 0.5
> g1 0.00 0.000 0.000 0.0
> g2 0.00 0.000 0.000 0.0

[[1]][[2]]
     ob0    ob1    ob2  obN
g0 0.245 0.0025 0.0025 0.25
g1 0.100 0.0500 0.1000 0.25
g2 0.000 0.0000 0.0000 0.00

[[1]][[3]]
   ob0 ob1 ob2 obN
g0 0.0 0.0 0.0 0.0
g1 0.2 0.1 0.2 0.5
g2 0.0 0.0 0.0 0.0

[[2]]
[[2]][[1]]
     ob0    ob1    ob2  obN
g0 0.245 0.0025 0.0025 0.25
g1 0.100 0.0500 0.1000 0.25
g2 0.000 0.0000 0.0000 0.00

[[2]][[2]]
       ob0     ob1     ob2   obN
g0 0.12250 0.00125 0.00125 0.125
g1 0.10000 0.05000 0.10000 0.250
g2 0.00125 0.00125 0.12250 0.125

[[2]][[3]]
      ob0    ob1   ob2  obN
g0 0.0000 0.0000 0.000 0.00
g1 0.1000 0.0500 0.100 0.25
g2 0.0025 0.0025 0.245 0.25

[[3]]
[[3]][[1]]
   ob0 ob1 ob2 obN
g0 0.0 0.0 0.0 0.0
g1 0.2 0.1 0.2 0.5
g2 0.0 0.0 0.0 0.0

[[3]][[2]]
      ob0    ob1   ob2  obN
g0 0.0000 0.0000 0.000 0.00
g1 0.1000 0.0500 0.100 0.25
g2 0.0025 0.0025 0.245 0.25

[[3]][[3]]
     ob0   ob1  ob2 obN
g0 0.000 0.000 0.00 0.0
g1 0.000 0.000 0.00 0.0
g2 0.005 0.005 0.49 0.5

**Comment by rossibarra** [comment]
No I think the missing column has to stay all 1.

**Comment by yangjl** [comment]
Agreed. I figured it out. I think you are right.
